unique_ids:
  assets:
    standard-page.html: VEGN2JYE6ZORZOTTOZDDKH72NQQU6CFD
    theme.css: XRE5BS2X3AT6CRJBBJOOXAQ5YLI5XLZU
  forms:
    Form1: '172549311853276242958828.9275'
  modules: {}
  scripts: {}
  server_modules: {}
